---
title: "Parking Lot"
format: html
---




## What is a Repository?

A repository is a structured way of storing code or text. It keeps track of each change that you make to the code, and it allows multiple people to work on versions of their code to combine them.


## What is Usually Stored in a Repository?

- Text 
- Code
- Webpages


## Whats the difference between Git and GitHub?

- Git is a program that allows you to work with local versions of your repositories
- GitHub is a website that hosts your repository in a central location. It uses Git underneath, but it also has social parts to it as well.
## Tour of a repository in GitHub

- Biodev


## How do we collaborate using a repo?

- We all have copies of code in repo
- These copies are not synced until we manually sync, they are separate
- We can split off branches 
- We can "check-in" changes we make to the code, and other people can "check out" these code changes
- If two of us are modifying the same code, then we need to resolve these changes into a single set of changes

# "Check ins" are called *commits*


## Working together in a Repo

- Make a branch for your own work
- Making commits to your own branch
- Resolving changes to the codebase

## Branching

- 

## Pull Requests


## Essential concepts

- Repository
- Commit
- Diff
- Branch
- Pull Request

### Create two repositories

- Member of one, external to another
- Contribute to your own
- Contribute to someone else's, by PR 

## Requirements

- GitHub account (send me your userid)
- 